### ISSUE TITLE
При пополнении баланса определенной суммой, вместо баланса отображается сумма пополнения

### ISSUE THREAD

**Issue by EgorKustov** [EgorKustov/TeamProject#1]
# Описание
Когда мы пытаемся пополнить баланс на определенную сумму, и после запрашиваем баланс, то нам отображается сумма пополнения.

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Зайти в public class CreditAccountTest.
3. Создать тест testAddWithPositiveAmountAndNegativeBalance.
4. Заполнить значение переменной `initialBalance значением` "-100"
5. Заполнить значение переменной `creditLimit` значением "500"
6. Заполнить значение переменной `rate` значением "10"
7. Пополнить баланс на 150 
8. Сравнить c ожидаемым результатом
9. Посмотреть вывод в консоли

*Ожидаемый результат:* Актуальный результат и ожидаемый совпадают
*Фактический результат:* Ожидаемый результат 50, а актуальный 150

https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L21-L32

# Скриншот
![image](https://github.com/EgorKustov/TeamProject/assets/138770642/921e2341-9946-423f-943c-077f31b3da41)

# Окружение
Операционная система: Windows 10 Pro 19045.3448
IDE: IntelliJ IDEA 2023.2.2
Java: OpenJDK 11

**Comment by DianaKhorosavina** [comment]
Fixed
