### ISSUE TITLE
При оплате покупки на сумму больше чем на сберегательном счету, баланс счета становится отрицательным

### ISSUE THREAD

**Issue by DianaKhorosavina** [EgorKustov/TeamProject#10]
# Описание
При оплате покупки со сберегательного счета на сумму превышающую сумму баланс, баланс становится отрицательным 

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/679c2fa863002f783a83c82ad4ad460ad09a7f2c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть код программы в IDEA.
2. Зайти в public class SavingAccountTest.
3. Создать тест shouldNotPayMoreThanBalance.
4. Заполнить значение параметра ` initialBalance: 1_000 `. 
5. Заполнить значение параметра ` minBalance: 0`.
6. Заполнить значение параметра ` maxBalance: 5_000 `. 
7. Заполнить значение параметра ` rate: 2 `.
8. Заполнить значение параметра `account.pay(3_000)`.
9. Запустить тест.
10. Сравнить c ожидаемым результатом.
11. Посмотреть вывод в консоли.

*Ожидаемый результат:* На балансе счета 1_000.
*Фактический результат:* На балансе счета -2_000.

https://github.com/EgorKustov/TeamProject/blob/10c35324e10e2e4c0e3ec52da1c48cde36da37e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L157C4-L172C6

# Скриншот  
![Баг4](https://github.com/EgorKustov/TeamProject/assets/143611523/02b04084-199a-4b74-8943-84566cd03bc3)

# Окружение
* **Операционная система:** Windows 11, версия 22H2, сборка: 22621.1992
* **IDE:** IntelliJ IDEA 2023.2.2. (Community Edition)
*  **Java:** OpenJDK 11

**Comment by EgorKustov** [comment]
Fixed
