### ISSUE TITLE
Остаток по сберегательному счету после оплаты покупки меньше чем минимальный баланс

### ISSUE THREAD

**Issue by DianaKhorosavina** [EgorKustov/TeamProject#11]
# Описание
При оплате покупки остаток по счету меньше чем минимальный баланс по сберегательному счету.

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/679c2fa863002f783a83c82ad4ad460ad09a7f2c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть код программы в IDEA.
2. Зайти в public class SavingAccountTest.
3. Создать тест shouldNotPayMoreThanMinBalance.
4. Заполнить значение параметров ` initialBalance: 3_000 `. 
5. Заполнить значение параметров ` minBalance: 2_000 `.
6. Заполнить значение параметров ` maxBalance: 5_000 `. 
7. Заполнить значение параметров ` rate: 2 `.
8. Заполнить сумму покупки `account.pay(3_000)`.
9. Запустить тест.
10. Сравнить c ожидаемым результатом.
11. Посмотреть вывод в консоли.

*Ожидаемый результат:* На балансе счета 3_000.
*Фактический результат:* На балансе счета 0.

https://github.com/EgorKustov/TeamProject/blob/10c35324e10e2e4c0e3ec52da1c48cde36da37e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L175C2-L190C5

# Скриншот  
![Баг5](https://github.com/EgorKustov/TeamProject/assets/143611523/4f55fd6d-41db-4144-9a49-6e87a9a28de0)

# Окружение
* **Операционная система:** Windows 11, версия 22H2, сборка: 22621.1992
* **IDE:** IntelliJ IDEA 2023.2.2. (Community Edition)
*  **Java:** OpenJDK 11

**Comment by EgorKustov** [comment]
fixed
