### ISSUE TITLE
Баланс сберегательного счета становится отрицательным, при оплате покупки на сумму больше чем максимальный баланс

### ISSUE THREAD

**Issue by DianaKhorosavina** [EgorKustov/TeamProject#12]
# Описание
При оплате покупки на сумму больше чем максимальный баланс сберегательного счета, баланс счета становится отрицательным

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/679c2fa863002f783a83c82ad4ad460ad09a7f2c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть код программы в IDEA.
2. Зайти в public class SavingAccountTest.
3. Создать тест shouldNotPayMoreThanMaxBalance.
4. Заполнить значение параметра ` initialBalance: 5_000 `. 
5. Заполнить значение параметра ` minBalance: 0 `.
6. Заполнить значение параметра ` maxBalance: 5_000 `. 
7. Заполнить значение параметра ` rate: 2 `.
8. Заполнить значение параметра `account.pay(5_100)`.
9. Запустить тест.
10. Сравнить c ожидаемым результатом.
11. Посмотреть вывод в консоли.

*Ожидаемый результат:* На балансе счета 5_000.
*Фактический результат:* На балансе счета -100.

https://github.com/EgorKustov/TeamProject/blob/10c35324e10e2e4c0e3ec52da1c48cde36da37e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L193C1-L209C6

# Скриншот  
![Баг6](https://github.com/EgorKustov/TeamProject/assets/143611523/ff1bcae5-3ef6-42b4-b643-df754388db69)

# Окружение
* **Операционная система:** Windows 11, версия 22H2, сборка: 22621.1992
* **IDE:** IntelliJ IDEA 2023.2.2. (Community Edition)
*  **Java:** OpenJDK 11

**Comment by EgorKustov** [comment]
Fixed
