### ISSUE TITLE
Покупка не совершается, если остаток по сберегательному счету равен минимальному балансу.

### ISSUE THREAD

**Issue by DianaKhorosavina** [EgorKustov/TeamProject#13]
# Описание
Нельзя совершить покупку, если после оплаты сумма остатка по сберегательному счету равна минимальному балансу по сберегательному счету

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/679c2fa863002f783a83c82ad4ad460ad09a7f2c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть код программы в IDEA.
2. Зайти в public class SavingAccountTest.
3. Создать тест shouldPayLessThanMinBalance.
4. Заполнить значение параметра ` initialBalance: 3_000 `. 
5. Заполнить значение параметра ` minBalance: 2_000 `.
6. Заполнить значение параметра ` maxBalance: 5_000 `. 
7. Заполнить значение параметра ` rate: 2 `.
8. Заполнить значение параметра `account.pay(1_000).`
9. Запустить тест.
10. Сравнить c ожидаемым результатом.
11. Посмотреть вывод в консоли.

*Ожидаемый результат:* true.
*Фактический результат:* false.
 
https://github.com/EgorKustov/TeamProject/blob/10c35324e10e2e4c0e3ec52da1c48cde36da37e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L212C1-L226C6

# Скриншот  
![Баг7](https://github.com/EgorKustov/TeamProject/assets/143611523/6c0a55e7-3945-4b0f-80de-13df46c3978e)

# Окружение
* **Операционная система:** Windows 11, версия 22H2, сборка: 22621.1992
* **IDE:** IntelliJ IDEA 2023.2.2. (Community Edition)
*  **Java:** OpenJDK 11

**Comment by EgorKustov** [comment]
Fixed
