### ISSUE TITLE
При попытке списать сумму больше, чем размер кредитного лимита, операция совершается

### ISSUE THREAD

**Issue by EgorKustov** [EgorKustov/TeamProject#2]
# Описание
Когда мы пытаемся списать сумму больше, чем размер кредитного лимита, операция совершается и баланс уходит за пределы кредитного лимита

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L47

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Зайти в public class CreditAccountTest.
3. Создать тест testPayExceedingCreditLimit
4. Заполнить значение переменной `initialBalance значением` "-200"
5. Заполнить значение переменной `creditLimit` значением "500"
6. Заполнить значение переменной `rate` значением "10"
7. Списать сумму 800. 
8. Сравнить c ожидаемым результатом
9. Посмотреть вывод в консоли

*Ожидаемый результат:* Так как баланс превысит размеры кредитного лимита, операция заблокируется и баланс останется прежним
*Фактический результат:* Списание средств проходит

https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L82-L93

# Скриншот
![image](https://github.com/EgorKustov/TeamProject/assets/138770642/fc884d5c-c6df-4aaa-90a9-8b81d024f0d1)

# Окружение
Операционная система: Windows 10 Pro 19045.3448
IDE: IntelliJ IDEA 2023.2.2
Java: OpenJDK 11

**Comment by DianaKhorosavina** [comment]
Fixed
