### ISSUE TITLE
Не правильные расчёты при покупке, которая не превышает кредитный лимит

### ISSUE THREAD

**Issue by EgorKustov** [EgorKustov/TeamProject#3]
# Описание
При попытке совершить покупку, которая переведёт баланс в минус, но не выйдет за пределы кредитного лимита, баланс высчитывается неправильно

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Зайти в public class CreditAccountTest.
3. Создать тест testPayMoreThanBalance.
4. Заполнить значение переменной `initialBalance значением` "100"
5. Заполнить значение переменной `creditLimit` значением "500"
6. Заполнить значение переменной `rate` значением "10"
7. Совершить покупку на 200 
8. Сравнить c ожидаемым результатом
9. Посмотреть вывод в консоли

*Ожидаемый результат:* Операция совершается, баланс равен -100
*Фактический результат:* Баланс становится равным -200

https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L94-L105

# Скриншот
![image](https://github.com/EgorKustov/TeamProject/assets/138770642/7eb83f05-367e-4c55-a836-86e2c5630bd1)

# Окружение
Операционная система: Windows 10 Pro 19045.3448
IDE: IntelliJ IDEA 2023.2.2
Java: OpenJDK 11

**Comment by DianaKhorosavina** [comment]
Fixed
