### ISSUE TITLE
Неверный расчёт при покупке

### ISSUE THREAD

**Issue by EgorKustov** [EgorKustov/TeamProject#4]
# Описание
При попытке совершить покупку, на которую, хватает средств, баланс высчитывается неправильно

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Зайти в public class CreditAccountTest.
3. Создать тест testPayStandartBalance.
4. Заполнить значение переменной `initialBalance значением` "500"
5. Заполнить значение переменной `creditLimit` значением "500"
6. Заполнить значение переменной `rate` значением "10"
7. Совершить покупку на 200 
8. Сравнить c ожидаемым результатом
9. Посмотреть вывод в консоли

*Ожидаемый результат:* Операция совершается, баланс равен 300
*Фактический результат:* Баланс становится равным -200

https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L106-L117

# Скриншот
![image](https://github.com/EgorKustov/TeamProject/assets/138770642/80669db8-7122-46cb-8177-9796ac34da81)

# Окружение
Операционная система: Windows 10 Pro 19045.3448
IDE: IntelliJ IDEA 2023.2.2
Java: OpenJDK 11

**Comment by DianaKhorosavina** [comment]
Fixed
