### ISSUE TITLE
При положительном балансе, начисляются проценты

### ISSUE THREAD

**Issue by EgorKustov** [EgorKustov/TeamProject#5]
# Описание
Баланс поддерживается положительным, но при подсчете процентов, они начисляются.

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L83

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Зайти в public class CreditAccountTest.
3. Создать тест testYearChangeWithPositiveBalance.
4. Заполнить значение переменной `initialBalance значением` "100"
5. Заполнить значение переменной `creditLimit` значением "500"
6. Заполнить значение переменной `rate` значением "10"
7. Запускаем тест 
8. Сравнить c ожидаемым результатом
9. Посмотреть вывод в консоли

*Ожидаемый результат:*Проценты не начислялись, так как баланс был положительным
*Фактический результат:* Проценты начислялись

https://github.com/EgorKustov/TeamProject/blob/074e98417cc6a578a887d83ae844a953d505b4ce/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L120-L129

# Скриншот
![image](https://github.com/EgorKustov/TeamProject/assets/138770642/c9ec9b6e-1828-4ab5-b2d8-08a360df3c78)

# Окружение
Операционная система: Windows 10 Pro 19045.3448
IDE: IntelliJ IDEA 2023.2.2
Java: OpenJDK 11

**Comment by DianaKhorosavina** [comment]
Fixed
