### ISSUE TITLE
При пополнении сберегательного счета указывает только сумму на которую счет пополняется

### ISSUE THREAD

**Issue by DianaKhorosavina** [EgorKustov/TeamProject#7]
# Описание
Если пополнить сберегательный счет на котором уже есть денежные средства, сумма на сберегательном счету не увеличивается, а отображается только сумма пополнения.

# Локация дефекта
https://github.com/EgorKustov/TeamProject/blob/679c2fa863002f783a83c82ad4ad460ad09a7f2c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть код программы в IDEA.
2. Зайти в public class SavingAccountTest.
3. Создать тест shouldAddLessThanMaxBalance.
4. Заполнить значение параметра ` initialBalance: 2_000 `. 
5. Заполнить значение параметра ` minBalance: 1_000 `.
6. Заполнить значение параметра ` maxBalance: 10_000 `. 
7. Заполнить значение параметра ` rate: 5 `.
8.  Заполнить значение параметра `account.add(3_000)`.
9. Запустить тест.
10. Сравнить c ожидаемым результатом.
11. Посмотреть вывод в консоли.

*Ожидаемый результат:* На балансе счета 5_000.
*Фактический результат:* На балансе счета 3_000.

https://github.com/EgorKustov/TeamProject/blob/10c35324e10e2e4c0e3ec52da1c48cde36da37e1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9C2-L21C6

# Скриншот  
![Баг 1](https://github.com/EgorKustov/TeamProject/assets/143611523/5a23acb0-7ce3-4d67-b9ef-97f0ce1c5673)

# Окружение
* **Операционная система:** Windows 11, версия 22H2, сборка: 22621.1992
* **IDE:** IntelliJ IDEA 2023.2.2. (Community Edition)
*  **Java:** OpenJDK 11

**Comment by EgorKustov** [comment]
Fixed
